### ISSUE TITLE
Tensorflow.js can't handle large datasets

### ISSUE THREAD

**Issue by lwthatcher** [lwthatcher/stickers#4]
# `Tensorflow.js` Cannot Handle Large Datasets
Currently in the merged `master` branch the route for the `run-pink` dataset fails to load because the dataset size is too large to create as a tensor. 

It looks like to get around this we'll have to switch over to parsing the data from .csv format.

## TODO:
- [x] convert dataset files to .csv format
- [x] update `dataloader.service.ts` to load data from .csv
- [x] update `server.js` to serve .csv files as well
- [x] update `databar.component.ts` to load data from .csv

## Error Message:
``` javascript
ERROR Error: Uncaught (in promise): Error: Requested texture size [21013x39] greater than WebGL maximum on this browser / GPU [16384x16384].
Error: Requested texture size [21013x39] greater than WebGL maximum on this browser / GPU [16384x16384].
    at Object.validateTextureSize (webgl_util.js:188)
    at createAndConfigureTexture (gpgpu_util.js:120)
    at Object.createMatrixTexture (gpgpu_util.js:137)
    at GPGPUContext.createMatrixTexture (gpgpu_context.js:109)
    at TextureManager.acquireTexture (texture_manager.js:32)
    at MathBackendWebGL.uploadToGPU (backend_webgl.js:829)
    at eval (backend_webgl.js:761)
    at Array.map (<anonymous>)
    at MathBackendWebGL.compileAndRun (backend_webgl.js:760)
    at MathBackendWebGL.slice (backend_webgl.js:305)
    at Object.validateTextureSize (webgl_util.js:188)
    at createAndConfigureTexture (gpgpu_util.js:120)
    at Object.createMatrixTexture (gpgpu_util.js:137)
    at GPGPUContext.createMatrixTexture (gpgpu_context.js:109)
    at TextureManager.acquireTexture (texture_manager.js:32)
    at MathBackendWebGL.uploadToGPU (backend_webgl.js:829)
    at eval (backend_webgl.js:761)
    at Array.map (<anonymous>)
    at MathBackendWebGL.compileAndRun (backend_webgl.js:760)
    at MathBackendWebGL.slice (backend_webgl.js:305)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4751)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
defaultErrorLogger @ core.js:1449
ErrorHandler.handleError @ core.js:1510
next @ core.js:5508
schedulerFn @ core.js:4342
SafeSubscriber.__tryOrUnsub @ Subscriber.js:243
SafeSubscriber.next @ Subscriber.js:190
Subscriber._next @ Subscriber.js:131
Subscriber.next @ Subscriber.js:95
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4322
(anonymous) @ core.js:4782
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4708
onHandleError @ core.js:4782
ZoneDelegate.handleError @ zone.js:392
Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:677
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
(anonymous) @ http.js:2353
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:138
MergeMapSubscriber._tryNext @ mergeMap.js:135
MergeMapSubscriber._next @ mergeMap.js:118
Subscriber.next @ Subscriber.js:95
ScalarObservable._subscribe @ ScalarObservable.js:51
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:92
Observable.subscribe @ Observable.js:157
FilterOperator.call @ filter.js:61
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
(anonymous) @ Observable.js:286
ZoneAwarePromise @ zone.js:891
Observable.toPromise @ Observable.js:284
DataloaderService.fetchTensors @ dataloader.service.ts:31
DataloaderService.setDataset @ dataloader.service.ts:16
DataviewComponent.ngOnInit @ dataview.component.ts:25
checkAndUpdateDirectiveInline @ core.js:12411
checkAndUpdateNodeInline @ core.js:13935
checkAndUpdateNode @ core.js:13878
debugCheckAndUpdateNode @ core.js:14771
debugCheckDirectivesFn @ core.js:14712
(anonymous) @ DataviewComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:14697
checkAndUpdateView @ core.js:13844
callViewAction @ core.js:14195
execEmbeddedViewsAction @ core.js:14153
checkAndUpdateView @ core.js:13845
callViewAction @ core.js:14195
execComponentViewsAction @ core.js:14127
checkAndUpdateView @ core.js:13850
callWithDebugContext @ core.js:15098
debugCheckAndUpdateView @ core.js:14635
ViewRef_.detectChanges @ core.js:11619
(anonymous) @ core.js:5918
ApplicationRef.tick @ core.js:5918
(anonymous) @ core.js:5751
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4760
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4577
next @ core.js:5751
schedulerFn @ core.js:4342
SafeSubscriber.__tryOrUnsub @ Subscriber.js:243
SafeSubscriber.next @ Subscriber.js:190
Subscriber._next @ Subscriber.js:131
Subscriber.next @ Subscriber.js:95
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4322
checkStable @ core.js:4725
onHasTask @ core.js:4773
ZoneDelegate.hasTask @ zone.js:441
ZoneDelegate._updateTaskCount @ zone.js:461
Zone._updateTaskCount @ zone.js:285
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
```

**Comment by lwthatcher** [comment]
Fixed. The dataset format can now be specified for tensor or csv, to which it can now load both.

The plotting code is now agnostic to which format is being used by exposing a `Dataset` interface defined in the data-loader service.
